### ISSUE TITLE
Criar arquivo de dist - já minificado e transpilado - para usar em "frontend"

### ISSUE THREAD

**Issue by ppdeassis** [caiena/lodash-ext#1]
ref https://github.com/caiena/ship/issues/222

Precisamos criar um arquivo já minificado e transpilado para uso em _frontend_, evitando problemas como o reportado - IE11 não funciona por conta do `module.exports` e a não transpilação de uma Vue.app.

Para isso, usar a [cli do Babel](https://babeljs.io/docs/en/usage) para buildar o dist.
Deixá-lo idealmente em `dist/lodash-ext.${hash}.min.js`.

**Comment by alexbruno** [comment]
Fala @ppdeassis 
Eu posso contribuir um pouco aqui se quiser. Notei que há uma cópia dessa lib no Folha e vim conferir.
Outra melhoria que poderia ser implementada seria o suporte a tree shaking, para otimização de imports e builds.

**Comment by ppdeassis** [comment]
Oi, @alexbruno!
Estava fora esses dias. Legal, cara! Se conseguir subir um PR pra gente, fique à vontade.

**Comment by alexbruno** [comment]
Fala, voltei olhar pra cá um pouco.

Estou preparando aqui para contribuir com este projeto e fiquei com algumas dúvidas.

Há intenção de transformar o resultado em um módulo NPM?

Seria interessante para fácil instalação em qualquer projeto, com controle de versão, listagem em dependências, etc... Atualmente, pelo que vejo, é necessário baixar uma cópia manualmente ou via Git para obtê-lo.

**Comment by ppdeassis** [comment]
Oi, Alex!
Ele já está disponível como pacote no npm - `@caiena/lodash-ext`.

**Comment by alexbruno** [comment]
Não chegou a fazer o merge?

**Comment by ppdeassis** [comment]
Resolvido na `v0.3.x`.
Integramos o Rollup para gerar as _builds/bundles_, com formatos específicos para cada _environment_.

No `package.json`, estão explícitos:
```json
"main": "dist/lodash-ext.cjs.js",
"module": "dist/lodash-ext.esm.js",
"browser": "dist/lodash-ext.umd.js",
```

Mais avanços para facilitar futuro desenvolvimento em #5 .
