### ISSUE TITLE
Implementação de métodos

### ISSUE THREAD

**Issue by alexbruno** [caiena/lodash-ext#2]
Analisei um pouco o código dos métodos implementados.
Pelo que entendi, conceitualmente, a maior parte dessas implementações são para facilitar o uso por devs Ruby, comparando com métodos conhecidos nessa linguagem.
Ok, mas eu trago aqui algumas dúvidas e sugestões para contribuir:

### _.dig
Esta implementação é desnecessária, pois a lodash já possui um método bastante flexível e eficiente que faz exatamente a mesma coisa:

https://lodash.com/docs/#get

A sintaxe de uso é um pouco diferente e ainda traz a opção de passar no último argumento um valor default, caso o valor buscado não seja encontrado.

Se houver a necessidade de manter este método com a sintaxe atual devido ao uso em outros projetos, basta simplesmente fazermos ele retornar o que o método *get* já faz:

```javascript
function dig (object, ...keys) {
  return _.get(object, keys)
}
```

### _.isBlank
Entendi aqui a ideia de fornecer um método que funcione de forma que devs Ruby/Rails entendam, mas isso impede que os devs entendam como o JS funciona.

A própria lodash não implementa um método como esse porque isso é desnecessário no JS, pois uma validação desse tipo é feita com um simples `if` ou um operador unário.

Na própria issue citada no comentário do código há uma resposta mostrando a simplicidade disso no JS nativo.

https://github.com/lodash/lodash/issues/2261#issuecomment-211376880

Implementar um método como esse torna o uso do JS mais complexo e confuso. Ao se desenvolver em JS é importante entender como o JS funciona.

Por exemplo, se eu for desenvolver em Ruby, não vou querer fazê-lo funcionar como JS, vou tentar entender o Ruby.

**Comment by ppdeassis** [comment]
Fala, @alexbruno!

Só vi agora. Obrigado pelo interesse! 
Vamos lá:

# `_.dig(object, ...keys)`

Sim, a ideia é trazer a similaridade/naturalidade para devs Ruby.

Concordo com vc! Inclusive, atualmente o [método está de fato usando o `_.get()`](https://github.com/caiena/lodash-ext/blob/master/src/dig.js#L20) - com alguns ajustes no seu _snipped_ para construir o _path_ que o lodash usa.

Acredito que possamos remover o método num futuro não distante (após passar por um período de depreciação, claro).


# `_.isBlank(val)`

Sim, a ideia é trazer a facilidade que o ActiveSupport traz com os métodos `.blank?` e `.present?` no Ruby. Temos muitos engenheiros na Caiena que passam o dia transitando entre Ruby e JS. Qualquer similaridade apóia bastante aqui! (Mas nada _tão_ extramo como o [RubyJS](http://rubyjs.org) 😂)

Não é exatamente tão simples como um `if` ou `!` unário. Basta tentar valores como:
- `false`
- `0`
- `'   '` (string somente com espaços)
- `[]` (array vazio)
- `{}`
- ... enfim

Não concordo que torne o JS mais complexo e confuso, mesmo porque o uso do método é opcional. 😄

Imagine validações de dados numa API Node - que é um caso real de aplicação e que estimulou sua criação - o método ajuda bastante. Agora avance mais para validações no _client_ - também facilita a detecção de "presença" de dado.

O `lodash` não incorporar é uma decisão que eu até concordo: eles incentivam sempre a criação de _extensões/plugins_ com os métodos `core` que a lib fornece.



Valeu!

**Comment by alexbruno** [comment]
Eu entendo o que disse sobre o `_.isBlank`, mas ao contrário do que você disse, sim, todos os valores que você citou como exemplo podem ser testados com um simples `if`.
Basta conhecer a linguagem e entender as coisas como ela entende.
Tudo bem, se essa conveniência ajuda os devs de maior experiência Ruby e funciona pra galera na Caiena, beleza. Mas de fato distorce o entendimento de como o JS funciona.

**Comment by ppdeassis** [comment]
Falla, @alexbruno!

Vamos lá: a ideia do `isBlank` é uma detecção de "presença" - "o dado foi informado/preenchido?" -, que é diferente de booleano `true/false`.
Por exemplo: indicar `false` quer dizer que eu _preenchi_ o dado. Ou seja, `isBlank(false) === false`.

Vamos para os casos citados:
- `!false === true`, `_.isBlank(false) === false`
- `!0 === true`, `_.isBlank(0) === false`
- `!'   ' === false`, `_.isBlank('  ') === true`
- `![] === false`, `_.isBlank([]) === true`
- `!{} === false`, `_.isBlank({}) === true`

Ou seja, o `_isBlank()` unifica um processamento de "foi preenchido?" para qqer tipo de dado.
